services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api
    container_name: libera-front
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      api:
        condition: service_healthy
    networks:
      - libera_network

  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: libera-api
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - NODE_HOST=${NODE_HOST}
      - NODE_PORT=${NODE_RED_PORT}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - MP_ACCESS_TOKEN=${MP_ACCESS_TOKEN}
      - MP_DEFAULT_PAYER_ID=${MP_DEFAULT_PAYER_ID}
      - MP_DEFAULT_PAYER_EMAIL=${MP_DEFAULT_PAYER_EMAIL}
    networks:
      - libera_network


  ngrok:
    image: ngrok/ngrok@sha256:07bd8fa758e73489d3ba5a2fc95d912e0b8359ebfca4a55886e2059c10020da4
    container_name: libera-ngrok
    restart: unless-stopped
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "api:8080"
    networks:
      - libera_network
    depends_on:
      - api

networks:
  libera_network:
    driver: bridge

