spring.application.name=OpenIt

spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

node.url=http://${NODE_HOST:localhost}:${NODE_PORT:1880}/abrir
server.port=${PORT:8080}

mercadopago.access-token=${MP_ACCESS_TOKEN}
mercadopago.default-payer-id=${MP_DEFAULT_PAYER_ID}
mercadopago.default-payer-email=${MP_DEFAULT_PAYER_EMAIL:}
mercadopago.notification-url=${WEBHOOK_URL:}

